---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: odf-public-cluster
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  config: '{
        "cniVersion": "0.3.1",
        "type": "macvlan",
        "master": "bond1",
        "mode": "bridge",
        "ipam": {
            "type": "whereabouts",
            "range": "10.0.108.0/24"
        }
  }'