# EXAMPLE SECRET
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-ingress-secret
  namespace: openshift-ingress
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: ingress-certificate
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: ingress-certificate
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: ingress-certificate
        property: tls.key