apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../base/

helmCharts:
- name: infra-nodes
  version: 1.0.0
  valuesFile: values.yaml
  releaseName: infra-nodes-1.0.0
