---
default:
  app:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
    enabled: true
    enableAutoSync: false  # temporary 
    autoSyncPrune: false
    project: cluster-config
    destination:
      namespace: openshift-gitops
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/Yantra-Vinyasa/multi-cluster-configs.git
      targetRevision: main
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true  
    - FailOnSharedResource=true
    - RespectIgnoreDifferences=true
    - CreateNamespace=false
    syncPolicyRetry:
      limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy

projects:
  cluster-config:
    annotations:
      argocd.argoproj.io/sync-wave: '-2'
    description: Project for overall cluster configuration
    namespace: openshift-gitops
    sourceRepos:
    - https://github.com/Yantra-Vinyasa/multi-cluster-configs.git
    destinations: |
      - namespace: '*'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'

applications:


  infra-nodes:
    annotations:
      argocd.argoproj.io/sync-wave: '1'
      argocd.argoproj.io/sync-options: ServerSideApply=true
    source:
      path: cluster-configs/overlays/dev/infra-nodes


  cluster-proxy:
    annotations:
      argocd.argoproj.io/sync-wave: '2'
      argocd.argoproj.io/sync-options: ServerSideApply=true
    source:
      path: cluster-configs/overlays/dev/cluster-proxy

  pacman:
    annotations:
      argocd.argoproj.io/sync-wave: '3'
    source:
      path: cluster-configs/overlays/dev/pacman

  chrony:
    annotations:
      argocd.argoproj.io/sync-wave: '10'
    source:
      path: cluster-configs/overlays/dev/chrony
  
  etcd-backup:
    annotations:
      argocd.argoproj.io/sync-wave: '15'
    source:
      path: overlays/dev/etcd-backup
    extraFields: |
      ignoreDifferences:
        - name: trusted-ca-bundle
          kind: ConfigMap
          jsonPointers:
          - /data

  web-terminal-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '20'
    source:
      path: cluster-configs/overlays/dev/web-terminal-operator

  etherpad:
    annotations:
      argocd.argoproj.io/sync-wave: '30'
    source:
      path: cluster-configs/overlays/dev/etherpad

  openshift-servicemesh:
    annotations:
      argocd.argoproj.io/sync-wave: '40'
    source:
      path: cluster-configs/overlays/dev/openshift-servicemesh

  openshift-serverless:
    annotations:
      argocd.argoproj.io/sync-wave: '50'
    source:
      path: cluster-configs/overlays/dev/openshift-serverless

  nfd:
    annotations:
      argocd.argoproj.io/sync-wave: '60'
    source:
      path: cluster-configs/overlays/dev/nfd

  gpu-operator-certified:
    annotations:
      argocd.argoproj.io/sync-wave: '70'
    source:
      path: cluster-configs/overlays/dev/gpu-operator-certified

  authorino-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '80'
    source:
      path: cluster-configs/overlays/dev/authorino-operator