---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../../../base/odf-operator/"
patches:
  - path: patch-sub.yaml
    target:
      group: operators.coreos.com
      kind: Subscription
      name: odf-operator
      namespace: openshift-storage
      version: v1alpha1
