---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gatekeeper-operator-group
  namespace: openshift-gatekeeper-operator
spec:
  targetNamespaces:
    - openshift-gatekeeper-operator