---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gatekeeper-operator-sub
  namespace: openshift-gatekeeper-operator
spec:
  source: community-operators
  sourceNamespace: openshift-marketplace
  name: gatekeeper-operator
  channel: stable
  installPlanApproval: Manual