apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: post-trident-nfs
provisioner: csi.trident.netapp.io
parameters: 
  backendType: ontap-nas
allowVolumeExpansion: true
volumeBindingMode: Immediate