---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |+
    alertmanagerMain: {}
    prometheusK8s:
      retention: 7d
    prometheusOperator: {}
    k8sPrometheusAdapter: {}
    kubeStateMetrics: {}
    telemeterClient: {}
    openshiftStateMetrics: {}
    thanosQuerier: {}
