apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../../base/gpu-operator-certified/"
  

components:
  - components/mig-single

patches:
  - target:
      kind: Subscription
      name: gpu-operator-certified
    path: patch-channel.yaml
