---
apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: lso-volumeset
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: cluster.ocs.openshift.io/openshift-storage
        operator: Exists
  tolerations:
  - effect: NoSchedule
    key: node.ocs.openshift.io/storage
    operator: Equal
    value: "true"
  deviceInclusionSpec:
    deviceTypes:
    - disk
    minSize: PATCH_ME 
    maxSize: PATCH_ME 
  storageClassName: lso-volumeset
  volumeMode: Block
  maxDeviceCount: PATCH_ME 
...
