apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator/namespace.yaml
  - operator/operator-group.yaml
  - operator/subscription.yaml


  - instance/datasciencecluster.yaml
  - instance/dsc-init.yaml
  - instance/namespace.yaml
  - instance/odhdashboardconfig.yaml
