---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

resources:
- ../../../base/web-terminal-operator/operator

patches:
- path: patch-channel.yaml
  target:
    kind: Subscription
