---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../../../base/apiserver/"
patches:
  - path: patch-dnsname.yaml
    target:
      kind: APIServer
      name: cluster
      version: v1