---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: patient-portal-frontend

resources:
- resources/patient-portal-frontend-deployment.yaml
- resources/patient-portal-frontend-service.yaml
- resources/patient-portal-frontend-route.yaml
- resources/namespace.yaml
