---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openldap
  name: openldap
spec:
  serviceAccount: openldap
  selector:
    matchLabels:
      app: ldap
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap
    spec:
      serviceAccount: openldap
      containers:
        - name: container
          image: rroemhild/test-openldap
          ports:
            - containerPort: 8080
              protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
