---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openldap
  namespace: openldap
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openldap-anyuid
  namespace: openldap
subjects:
  - kind: ServiceAccount
    name: openldap
    namespace: openldap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'