---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - "../../../base/openshift-servicemesh/"


patches:
  - path: patch-channel.yaml
    target:
      group: operators.coreos.com
      kind: Subscription
      name: servicemeshoperator
      namespace: openshift-operators
      version: v1alpha1

# Removing the smcp resource from the base
  - patch: |-
      $patch: delete
      apiVersion: maistra.io/v2
      kind: ServiceMeshControlPlane
      metadata:
        name: istio-system
        namespace: istio-system