---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/ingress-controller.yaml
  # - resources/vault-ingress-secret.yaml # Sealed-secret, vault secret etc for the certificate