apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../base/

helmCharts:
- name: argocd-app-of-app-chart
  version: 0.4.0
  valuesFile: values.yaml
  releaseName: argocd-app-of-app-0.4.0
