apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- instance/keycloak.yaml
- instance/route.yaml
- operator/namespace.yaml
- operator/operator-group.yaml
- operator/subs.yaml
