apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../base/
  
helmCharts:
- name: alertmanager-config
  releaseName: alertmanager-config
  valuesFile: values.yaml

