---
default:
  app:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
    enabled: true
    enableAutoSync: false
    autoSyncPrune: false
    project: cluster-config
    destination:
      namespace: openshift-gitops
      server: https://kubernetes.default.svc
    source:
      repoURL: https://my-gitlab.example.com
      targetRevision: main

projects:
  cluster-config:
    annotations:
      argocd.argoproj.io/sync-wave: '-2'
    description: Project for overall cluster configuration
    namespace: openshift-gitops
    sourceRepos:
    - https://my-gitlab.example.com/openshift-config.git
    destinations: |
      - namespace: '*'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'

applications:


  infra-nodes:
    annotations:
      argocd.argoproj.io/sync-wave: '1'
      argocd.argoproj.io/sync-options: ServerSideApply=true
    source:
      path: cluster-configs/overlays/dev/infra-nodes


  cluster-proxy:
    annotations:
      argocd.argoproj.io/sync-wave: '2'
      argocd.argoproj.io/sync-options: ServerSideApply=true
    source:
      path: cluster-configs/overlays/dev/cluster-proxy

  pacman:
    annotations:
      argocd.argoproj.io/sync-wave: '3'
    source:
      path: cluster-configs/overlays/dev/pacman

  chrony:
    annotations:
      argocd.argoproj.io/sync-wave: '10'
    source:
      path: cluster-configs/overlays/dev/chrony
  
  etcd-backup:
    annotations:
      argocd.argoproj.io/sync-wave: '15'
    source:
      path: overlays/dev/etcd-backup
    extraFields: |
      ignoreDifferences:
        - name: trusted-ca-bundle
          kind: ConfigMap
          jsonPointers:
          - /data
