---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/apiserver.yaml
  # - resources/vault-api-secret.yaml # Sealed-secret, vault secret etc for the certificate