---
kind: Namespace
apiVersion: v1
metadata:
  name: etcd-backup
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    security.openshift.io/scc.podSecurityLabelSync: 'false'
  annotations:
    openshift.io/node-selector: 'node-role.kubernetes.io/master='
    scheduler.alpha.kubernetes.io/defaultTolerations: >-
      [{"operator": "Exists", "effect": "NoSchedule", "key":
      "node-role.kubernetes.io/master"}
      ]
spec: {}
