---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-s3-credentials
  namespace: etcd-backup
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: s3-credentials
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: s3-credentials
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_BUCKET_ID
      remoteRef:
        key: s3-credentials
        property: AWS_BUCKET_ID
    - secretKey: AWS_CLI_OPTIONS
      remoteRef:
        key: s3-credentials
        property: AWS_CLI_OPTIONS
    - secretKey: AWS_ENDPOINT_URL
      remoteRef:
        key: s3-credentials
        property: AWS_ENDPOINT_URL
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: s3-credentials
        property: AWS_SECRET_ACCESS_KEY
