---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/openshift-logging/

patches:
# Patches the subscription channel
- path: clusterlogging-patch-channel.yaml
  target:
    kind: Subscription
    name: cluster-logging

- path: loki-patch-channel.yaml
  target:
    kind: Subscription
    name: loki-operator

- path: loki-patch-retention.yaml
  target:
    kind: LokiStack
    name: logging-loki
