apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator/namespace.yaml
  - operator/operator-group.yaml
  - operator/subscription.yaml

  - instance/knative-serving/knative-serving-instance.yaml
  - instance/knative-serving/namespace.yaml

  - instance/knative-eventing/knative-eventing-instance.yaml
  - instance/knative-eventing/namespace.yaml