name: Check Spelling
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "test-workflow"

jobs:
  lint-spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.37.0
      name: Spellcheck
      with:
        config_path: .github/spellcheck.yml 
